/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package girlscoutcookieorder;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String userVariety = "";
        int userNumberOfBoxes = 0;
        boolean cookieChecker = true;
        String userInput = "";
        Orders userCookieOrder = new Orders();
        Scanner input = new Scanner(System.in);
        System.out.println("Greetings. It's cookie time!!");
        do {
            System.out.println("Enter \"y\" to order cookies.");
            System.out.println("Enter \"1\" to see your current order.");
            System.out.println("Enter \"n\" to exit.");
            System.out.println("Enter \"r\" to remove an item.");
            userInput = input.nextLine();
            userInput = userInput.trim().toLowerCase();
            if (userInput.equals("y")) {
                System.out.println("Please enter the type of cookies you would like:");
                userVariety = input.nextLine();
                System.out.println("Please enter the number of boxes you would like:");
                userNumberOfBoxes = Integer.parseInt(input.nextLine());
                System.out.println("Adding " + userNumberOfBoxes + " " + userVariety + " to your order.");
                Variety newOrder = new Variety(userVariety, userNumberOfBoxes);
                userCookieOrder.addVariety(newOrder);
            } else if (userInput.equals("n")) {
                if (userCookieOrder.getTotalBoxes() == 0) {
                    System.out.println("Boooooooo, way to not order cookies.");
                } else {
                    System.out.println(userCookieOrder.getTotalBoxes());
                    userCookieOrder.displayTotalOrder();
                }
                cookieChecker = false;
            } else if (userInput.equals("1")) {
                userCookieOrder.displayTotalOrder();
            } else if (userInput.equals("r")) {
                System.out.println("Please type the name of the item you would like to remove:");
                String userRemoveVariety = input.nextLine().trim().toLowerCase();
                System.out.println("Please type the quantity of the item you would like removed.");
                System.out.println(
                        "For example, enter \"1\" if you want to remove one box of " + userRemoveVariety + ".");
                int userRemoveQuantity = Integer.parseInt(input.nextLine());
                boolean removed = userCookieOrder.removeVariety(userRemoveVariety, userRemoveQuantity);
                if (removed) {
                    System.out.println(
                            "Removed " + userRemoveQuantity + " " + userRemoveVariety + " boxes from your order.");
                } else {
                    System.out.println("Hmmmm. Item not found or invalid amount, please try again.");
                }
            }

        } while (cookieChecker);
        input.close();
    }
}
